<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LedgerController;
use App\Http\Controllers\PacketController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ResellerController;
use Illuminate\Support\Facades\Route;

// Redirect root ke dashboard
Route::get('/', fn() => redirect()->route('dashboard'));

// Auth routes (generated by Breeze)
require __DIR__.'/auth.php';

// Semua route butuh login
Route::middleware('auth')->group(function () {

    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Profile (Breeze default)
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Master Data: Reseller
    Route::resource('resellers', ResellerController::class)->except(['show']);

    // Master Data: Paket
    Route::resource('packets', PacketController::class)->except(['show']);

    // Nasabah
    Route::resource('customers', CustomerController::class);
    Route::post('/customers/{customer}/add-packet', [CustomerController::class, 'addPacket'])->name('customers.add-packet');
    Route::patch('/customer-packets/{customerPacket}/status', [CustomerController::class, 'updatePacketStatus'])->name('customer-packets.update-status');

    // Setoran / Buku Tabungan
    Route::prefix('ledger')->name('ledger.')->group(function () {
        Route::get('/bulk-input', [LedgerController::class, 'bulkInput'])->name('bulk-input');
        Route::post('/bulk-store', [LedgerController::class, 'bulkStore'])->name('bulk-store');
        Route::get('/history/{customerPacket}', [LedgerController::class, 'history'])->name('history');
        Route::delete('/{savingsLedger}', [LedgerController::class, 'destroy'])->name('destroy');
    });
});
